--OBTENER APELLIDO Y OFICIO DE LOS EMPLEADOS 
--QUE TIENEN EL MISMO 
--OFICIO Y EL MISMO DEPARTAMENTO QUE EL DEPARTAMENTO DE INVESTIGACION

SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO) IN (SELECT OFICIO
                        FROM EMPLE
                        WHERE DEPT_NO = (SELECT DEPT_NO
                                        FROM DEPARTAMENTOS
                                        WHERE UPPER(DNOMBRE)='INVESTIGACION'));
--OTRA MANERA

SELECT APELLIDO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO) IN (SELECT DISTINCT E.OFICIO
FROM EMPLE E, DEPARTAMENTOS D
WHERE E.DEPT_NO = D.DEPT_NO
AND UPPER(D.DNOMBRE) = 'INVESTIGACION')                             
;



--VISUALIZAR EL NUMERO DE DEPARTAMENTO, EL OFICIO Y EL SALARIO 
--DE LOS EMPLEADOS CON MAYOR SALARIO DE CADA DEPARTAMENTO

SELECT DISTINCT DEPT_NO, OFICIO, SALARIO
FROM EMPLE E;

SELECT DEPT_NO, APELLIDO, OFICIO, SALARIO
FROM EMPLE E 
WHERE SALARIO IN (SELECT MAX(SALARIO)
                FROM EMPLE EM
                WHERE EM.DEPT_NO = E.DEPT_NO);
                
--ELIMINAR LOS DEPARTAMENTOS QUE TIENEN MENOS DE 2 EMPLEADOS

SELECT count(EMP_NO), DEPT_NO
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*) >=2;

DELETE FROM DEPART
WHERE DEPT_NO NOT IN (SELECT DEPT_NO
                    FROM EMPLE E
                    GROUP BY DEPT_NO
                    HAVING COUNT(*) >=2);
                    
                    
--LE VAMOS A AUMENTAR EN 5000 A LOS EMPLEADOS
--CUYO DEPARTAMENTO NO ESTE EN MADRID

UPDATE EMPLE
SET SALARIO = SALARIO + 5000
WHERE DEPT_NO IN (SELECT D.DEPT_NO
                  FROM DEPART D
                  WHERE UPPER(LOC) != 'MADRID');
                         
                                                            