ALTER TABLE TIENDAS ADD CONSTRAINT TIE_INITCAP_CK CHECK (NOMBRE= INITCAP(NOMBRE));

/*DESC USER_CONSTRAINTS;
DESC USER_TABLES;*/
SELECT TABLE_NAME, OWNER, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS 
WHERE UPPER(TABLE_NAME) IN('TIENDAS','PEDIDOS','FABRICANTES','ARTICULOS','VENTAS');

ALTER TABLE PEDIDOS MODIFY  UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE VENTAS MODIFY  UNIDADES_VENDIDAS NUMBER(6);

ALTER TABLE TIENDAS ADD CONSTRAINT TIE_TOLEDO_CK CHECK (UPPER(PROVINCIA)!='TOLEDO');

ALTER TABLE PEDIDOS ADD PVP NUMBER(4) DEFAULT 0;
ALTER TABLE VENTAS ADD PVP NUMBER(4) DEFAULT 0;


ALTER TABLE PEDIDOS DROP COLUMN PVP;
ALTER TABLE VENTAS DROP COLUMN PVP;



