--Para averiguar las columnas

DESC DEPARTSEQ;

--PARA AGRANDAR EL TAMAÑO DEL DEPT_NO
ALTER TABLE DEPARTSEQ MODIFY DEPT_NO NUMBER(4);
DESC DEPARTSEQ;


INSERT INTO DEPARTSEQ(DEPT_NO, DNOMBRE) VALUES(DEPT_ID_SEQ.NEXTVAL, 'EDUCACION');
INSERT INTO DEPARTSEQ(DEPT_NO, DNOMBRE) VALUES(DEPT_ID_SEQ.NEXTVAL, 'ADMINISTRACION');

SELECT * FROM DEPARTSEQ;
