--1
INSERT INTO DEPART(DEPT_NO, DNOMBRE, LOC) VALUES (11,'CALIDAD','SANTANDER');

INSERT INTO EMPLE(EMP_NO, APELLIDO, OFICIO, SALARIO, FECHA_ALTA, DEPT_NO)  VALUES (7230,'AGUIRRE','EMPLEADO',4351,SYSDATE,11);
commit;

--2
UPDATE EMPLE SET SALARIO = SALARIO - SALARIO*0.1;
commit;

--3
SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO IN (40,10);

UPDATE EMPLE SET DEPT_NO = 40 WHERE DEPT_NO = 10;

SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO = 40;


/*
--OTRO METODO

SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE) IN ('PRODUCCION', 'CONTABILIDAD'));


UPDATE EMPLE 
SET DEPT_NO = (SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE)='PRODUCCION') 
WHERE DEPT_NO = 10;

SELECT DEPT_NO, EMP_NO
FROM EMPLE
WHERE DEPT_NO=(SELECT DEPT_NO FROM DEPART WHERE UPPER(DNOMBRE) = ('PRODUCCION'));

*/

commit;

--4
SELECT ID_JEFE, EMP_NO, APELLIDO
FROM EMPLE
WHERE ID_JEFE IN (7566, (SELECT ID_JEFE 
                            FROM EMPLE 
                            WHERE UPPER(APELLIDO)='TOVAR')) 

ORDER BY ID_JEFE;

UPDATE EMPLE 
SET ID_JEFE = (SELECT ID_JEFE 
                FROM EMPLE 
                WHERE UPPER(APELLIDO)='TOVAR') 
                
WHERE ID_JEFE = 7566;

SELECT ID_JEFE, EMP_NO
FROM EMPLE
WHERE ID_JEFE = (SELECT ID_JEFE 
                FROM EMPLE 
                WHERE UPPER(APELLIDO)='TOVAR');

commit;

--5
SELECT  EMP_NO, APELLIDO, SALARIO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO)='EMPLEADO' OR UPPER(APELLIDO)='MUÑOZ';

UPDATE EMPLE 
SET SALARIO = NVL((SELECT SALARIO 
                    FROM EMPLE 
                    WHERE APELLIDO = 'MUÑOZ'),0) 
                                
WHERE  OFICIO = 'EMPLEADO'; 

SELECT EMP_NO, APELLIDO, SALARIO, OFICIO
FROM EMPLE
WHERE UPPER(OFICIO)='EMPLEADO';


commit;

--6
SELECT EMP_NO, COMISION_PCT, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO 
                FROM DEPART 
                WHERE UPPER(LOC)='SANTANDER');

UPDATE EMPLE 
SET COMISION_PCT = 300 
WHERE DEPT_NO IN (SELECT DEPT_NO
                    FROM DEPART
                    WHERE UPPER(LOC)='SANTANDER');

SELECT EMP_NO, COMISION_PCT, DEPT_NO
FROM EMPLE
WHERE DEPT_NO = (SELECT DEPT_NO 
                    FROM DEPART 
                    WHERE UPPER(LOC)='SANTANDER');

commit;

--7
SELECT EMP_NO, APELLIDO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO 
                FROM DEPART 
                WHERE UPPER(DNOMBRE)='VENTAS');

DELETE FROM EMPLE 
WHERE DEPT_NO IN (SELECT DEPT_NO 
                    FROM DEPART 
                    WHERE UPPER(DNOMBRE)='VENTAS');

SELECT EMP_NO, DEPT_NO
FROM EMPLE
WHERE DEPT_NO IN (SELECT DEPT_NO 
                    FROM DEPART 
                    WHERE UPPER(DNOMBRE)='VENTAS');


commit;




SELECT * FROM EMPLE;
