--EJERCICIO 1
DROP TABLE ALUMNOS;
DROP TABLE PERSONAS;
DROP TABLE PROVINCIAS;
DROP TABLE CIUDADANOS;

/

CREATE TABLE ALUMNOS (
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(30) NOT NULL,
    EDAD NUMBER(2),
    CURSO NUMBER(1),
    CONSTRAINT ALU_DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT ALU_EDAD_CK CHECK (EDAD BETWEEN 5 AND 20),
    CONSTRAINT ALU_NOM_CK CHECK (NOMBRE = UPPER(NOMBRE)),
    CONSTRAINT ALU_CUR_CK CHECK (CURSO IN (1,2,3))
);  

--EJERCICIO 2

ALTER TABLE ALUMNOS ADD (
    SEXO VARCHAR2(1) NOT NULL CONSTRAINT ALU_SEX_CK CHECK(SEXO IN ('M','F')),
    IMPORTE NUMBER(10,2) DEFAULT 0
    );
    
--EJERCICIO 3

ALTER TABLE ALUMNOS DROP (EDAD);

ALTER TABLE ALUMNOS ADD (
    FECHA_NAC DATE,
    FECHA_ALTA DATE,
    CONSTRAINT FECHA_NAC_CK CHECK (FECHA_NAC < FECHA_ALTA)
    ); 

--HAY QUE BORRAR PRIMERO LA CONSTRAINT

ALTER TABLE ALUMNOS DROP(FECHA_NAC) CASCADE CONSTRAINTS;
    
--EJERCICIO 4

ALTER TABLE ALUMNOS RENAME COLUMN IMPORTE TO TASAS;

--EJERCICIO 5

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ALUMNOS';

--EJERCICIO 6

CREATE TABLE PROVINCIAS (
    COD_PROV NUMBER(2),
    NOM_PROV VARCHAR2(15),
    CONSTRAINT PROV_COD_PK PRIMARY KEY (COD_PROV) 
    );

CREATE TABLE PERSONAS (
    DNI VARCHAR2(8),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(25),
    POBLACION VARCHAR2(20),
    COD_PROV NUMBER(2),
    CONSTRAINT PERS_DNI_PK PRIMARY KEY (DNI),
    CONSTRAINT FK_ASS_1 FOREIGN KEY(COD_PROV) REFERENCES PROVINCIAS
    
    );
    
--EJERCICIO 7    

RENAME PERSONAS TO CIUDADANOS;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PROVINCIAS';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CIUDADANOS';
--EJERCICIO 8
DROP TABLE PROVINCIAS;
