--EJERCICIO 1

CREATE OR REPLACE VIEW DEPT_SUM AS( 
    SELECT D.DNOMBRE "DEPT_NOMBRE" , MIN(E.SALARIO) "SAL_MIN" ,
    MAX(E.SALARIO) "SAL_MAX" , TRUNC(AVG(E.SALARIO)) "SAL_MED"
    FROM EMPLE E, DEPART D
    WHERE E.DEPT_NO = D.DEPT_NO --JOIN
    GROUP BY E.DEPT_NO , D.DNOMBRE);
    
--COMPROBACION DE QUE SE HA CREADO LA VISTA

DESC DEPT_SUM;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME) = 'DEPT_SUM';
--COMPLEJA YA QUE TIENE MÁS DE UNA TABLA  
--Y UTILIZA FUNCIONES DE GRUPO

--EJERCICIO 2
DROP VIEW SAL_20;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME) = 'SAL_20' ;

--EJERCICIO 3

CREATE OR REPLACE VIEW DEPT_SALMAX AS 
    (SELECT DEPT_NO "COD_DEPART" , 
        TRUNC(MAX(SALARIO)) "SAL_MAX"
    FROM EMPLE
    GROUP BY DEPT_NO);
    
/*OTRA MANERA DE PONERLO
  
    CREATE OR REPLACE VIEW DEPT_SALMAX (COD_DEPART, SAL_MAX) 
    AS
    (SELECT DEPT_NO , 
        TRUNC(MAX(SALARIO))
    FROM EMPLE
    GROUP BY DEPT_NO);
*/
    
--COMPRUEBO QUE SE HA CREADO LA VISTA

DESC DEPT_SALMAX;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='DEPT_SALMAX';

--EJERCICIO 4

SELECT APELLIDO , SALARIO , DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E
WHERE SALARIO >(SELECT AVG(SALARIO) 
                FROM EMPLE
                WHERE DEPT_NO=E.DEPT_NO 
                GROUP BY DEPT_NO )
ORDER BY E.APELLIDO
;
                
SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE --JOIN DE DEPART Y DE LA VISTA
        AND E.DEPT_NO = D.DEPT_NO --JOIN DE EMPLE Y DEPARTAMENTO
        AND E.SALARIO > DS.SAL_MED --CONDICION DE QUE EL SALARIO SEA MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO
;                
                
                
--EJERCICIO 5

SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "CODIGO DEPARTAMENTO", DS.SAL_MED
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE --JOIN DE DEPART Y DE LA VISTA
        AND E.DEPT_NO = D.DEPT_NO --JOIN DE EMPLE Y DEPARTAMENTO
        AND E.SALARIO > DS.SAL_MED --CONDICION DE QUE EL SALARIO SEA MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO
;                
           
                
                
                
                
                
                