--EJERCICIO 1

CREATE OR REPLACE VIEW DEPT_SUM AS( 
    SELECT D.DNOMBRE "DEPT_NOMBRE" , MIN(E.SALARIO) "SAL_MIN" ,
    MAX(E.SALARIO) "SAL_MAX" , TRUNC(AVG(E.SALARIO)) "SAL_MED"
    FROM EMPLE E, DEPART D
    WHERE E.DEPT_NO = D.DEPT_NO --JOIN
    GROUP BY E.DEPT_NO , D.DNOMBRE);
    
--COMPROBACION DE QUE SE HA CREADO LA VISTA

DESC DEPT_SUM;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME) = 'DEPT_SUM';
--COMPLEJA YA QUE TIENE MÁS DE UNA TABLA  
--Y UTILIZA FUNCIONES DE GRUPO

--EJERCICIO 2
DROP VIEW SAL_20;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME) = 'SAL_20' ;

--EJERCICIO 3

CREATE OR REPLACE VIEW DEPT_SALMAX AS 
    (SELECT DEPT_NO "COD_DEPART" , 
        TRUNC(MAX(SALARIO)) "SAL_MAX"
    FROM EMPLE
    GROUP BY DEPT_NO);
    
/*OTRA MANERA DE PONERLO
  
    CREATE OR REPLACE VIEW DEPT_SALMAX (COD_DEPART, SAL_MAX) 
    AS
    (SELECT DEPT_NO , 
        TRUNC(MAX(SALARIO))
    FROM EMPLE
    GROUP BY DEPT_NO);
*/
    
--COMPRUEBO QUE SE HA CREADO LA VISTA

DESC DEPT_SALMAX;

SELECT VIEW_NAME , TEXT
FROM USER_VIEWS
WHERE UPPER(VIEW_NAME)='DEPT_SALMAX';

--EJERCICIO 4

SELECT APELLIDO , SALARIO , DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E
WHERE SALARIO >(SELECT AVG(SALARIO) 
                FROM EMPLE
                WHERE DEPT_NO=E.DEPT_NO 
                GROUP BY DEPT_NO )
ORDER BY E.APELLIDO
;
                
SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE --JOIN DE DEPART Y DE LA VISTA
        AND E.DEPT_NO = D.DEPT_NO --JOIN DE EMPLE Y DEPARTAMENTO
        AND E.SALARIO > DS.SAL_MED --CONDICION DE QUE EL SALARIO SEA MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO
;                
                
                
--EJERCICIO 5

SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "CODIGO DEPARTAMENTO", DS.SAL_MED
FROM EMPLE E, DEPT_SUM DS, DEPART D
WHERE DS.DEPT_NOMBRE = D.DNOMBRE --JOIN DE DEPART Y DE LA VISTA
        AND E.DEPT_NO = D.DEPT_NO --JOIN DE EMPLE Y DEPARTAMENTO
        AND E.SALARIO > DS.SAL_MED --CONDICION DE QUE EL SALARIO SEA MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO
;         

--Ejercicio 6

DROP TABLE CENTROS CASCADE CONSTRAINTS;

CREATE TABLE CENTROS (
ID NUMBER(2) GENERATED ALWAYS AS IDENTITY 
                                    start with 1
                                    maxvalue 99
                                    increment by 1
                                    nocycle nocache,
NOMBRE VARCHAR2(30) NOT NULL,
CALLE VARCHAR2(30),
NUMERO NUMBER(2),
CP VARCHAR2(5),
CIUDAD VARCHAR2(15),
PROVINCIA VARCHAR2(40),
TELEFONO VARCHAR2(9),
CONSTRAINT CENTROS_ID_PK PRIMARY KEY (ID)
);
     
--Pasos para la comprobacion de la tabla     
desc user_tables;     

select table_name
from user_tables
where upper(table_name)='CENTROS';

desc centros;

--COMPROBAR LAS COLUMNAS DE LA TABLA
DESC USER_CONSTRAINTS;
DESC USER_VONS_COLUMNS;

select c.constraint_name, c.constraint_type, cc.table_name, cc.column_name
from user_constraints c, user_cons_columns cc
where c.constraint_name = cc.constraint_name --JOIN
and upper(c.table_name) = 'CENTROS';

desc user_sequences;

select table_name, column_name, data_default
from user_tab_columns
where upper(table_name) = 'CENTROS';

select last_number, increment_by, min_value, max_value
from user_sequences
where sequence_name = 'ISEQ$$_328316';

--EJERCICIO 7

INSERT INTO CENTROS(NOMBRE,CALLE,NUMERO,CP,CIUDAD,PROVINCIA,TELEFONO)
VALUES ('NASA', 'FRANCIA',27,01010,'VITORIA','ALAVA',945874963);

select * from centros;

--EJERCICIO 8
CREATE INDEX IND_FK_DEPT
ON EMPLE(DEPT_NO);


--EJERCICIO 9
DESC USER_INDEXES;
SELECT INDEX_NAME, INDEX_TYPE, TABLE_NAME, UNIQUENESS
FROM USER_INDEXES
WHERE UPPER(TABLE_NAME)= 'EMPLE';

--EJERCICIO 10
DROP INDEX IND_FK_DEPT;

--EJERCICIO 11
DESC DEPART;

DROP INDEX IND_DEPT_DNOMBRE;

CREATE INDEX IND_DEPT_DNOMBRE
ON DEPART(UPPER(DNOMBRE));

--EJERCICIO 13
ALTER INDEX IND_DEPT_DNOMBRE MONITORING USAGE;

SELECT *
FROM V$OBJECT_USAGE;


--EJERCICIO 14
DESC USER_INDEXES;

SELECT MONITORING
FROM USER_INDEXES;

--NO SE ACTIVA EL INDICE, NO SE UTILIZA EL NOMBRE DE DEPARTAMENTO

SELECT *
FROM DEPART
WHERE UPPER(DNOMBRE) LIKE '%A%';
SELECT *
FROM V$OBJECT_USAGE;
--AQUI SI SE VISUALIZA POR QUE UTILIZAMOS EL UPPER IGUAL 
--QUE EN LA DEFINICIÓN DEL INDICE


ALTER INDEX IND_DEPT_DNOMBRE NOMONITORING USAGE;
SELECT *
FROM V$OBJECT_USAGE;--COMPROBACIÓN DE LA MONITORIZACION

--EJERCICIO 15
DROP PUBLIC SYNONYM DEP;
CREATE PUBLIC SYNONYM DEP
FOR DEPART;

--COMPROBAR QUE FUNCIONA EN SINONIMO
SELECT *
FROM DEP;

RENAME DEPART TO DEPARTAMENTOS;
RENAME DEPARTAMENTOS TO DEPART;
--COMPROBACION DEL CAMBIO DE NOMBRE

SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME) = 'DEPART';

SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME) = 'DEPARTAMENTOS';


DESC USER_SYNONYMS;

SELECT SYNONYM_NAME, TABLE_NAME, TABLE_OWNER
FROM USER_SYNONYMS 
WHERE UPPER(SYNONYM_NAME)='DEP';
/*
ORA-00980: la traducción del sinónimo ya no es válida
00980. 00000 -  "synonym translation is no longer valid"
*Cause:    A synonym did not translate to a legal target object. This
           could happen for one of the following reasons:
           1. The target schema does not exist.
           2. The target object does not exist.
           3. The synonym specifies an incorrect database link.
           4. The synonym is not versioned but specifies a versioned
           target object.
*Action:   Change the synonym definition so that the synonym points at
           a legal target object.
Error en la línea: 195, columna: 6

*/

--EL SINONIMO ESTA SOBRE LA TABLA DEPART Y NO EN DEPARTAMENTOS

DROP PUBLIC SYNONYM DEP;


CREATE SYNONYM DEP
FOR DEPARTAMENTOS;

SELECT *
FROM DEP;

 
SELECT SYNONYM_NAME, TABLE_NAME, TABLE_OWNER
FROM USER_SYNONYMS 
WHERE UPPER(SYNONYM_NAME)='DEP';


--EJERCICIO 16
DROP SYNONYM DEP1;
                
                
                
                
                
                