--EJERCICIO 1

SELECT APELLIDO, SALARIO, DEPT_NO FROM EMPLE WHERE SALARIO > 2000 AND DEPT_NO IN (10,20);

--EJERCICIO 2

SELECT APELLIDO, SALARIO FROM EMPLE WHERE (SALARIO > 1500 AND SALARIO < 2000);

--EJERCICIO 3

SELECT APELLIDO, DEPT_NO FROM EMPLE WHERE DEPT_NO IN (10, 30);

--EJERCICIO 4

SELECT APELLIDO, OFICIO,ID_JEFE FROM EMPLE  WHERE ID_JEFE IS NULL;
