
CREATE OR REPLACE VIEW DEPT_SUM2 AS( 
    SELECT E.DEPT_NO "COD_DEPT", D.DNOMBRE "DEPT_NOMBRE" , MIN(E.SALARIO) "SAL_MIN" ,
    MAX(E.SALARIO) "SAL_MAX" , TRUNC(AVG(E.SALARIO)) "SAL_MED"
    FROM EMPLE E, DEPART D
    WHERE E.DEPT_NO = D.DEPT_NO --JOIN
    GROUP BY E.DEPT_NO , D.DNOMBRE);
    
DESC DEPT_SUM2;


SELECT E.APELLIDO , E.SALARIO , E.DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E, DEPT_SUM2 DS
WHERE E.DEPT_NO = DS.COD_DEPT --JOIN DE EMPLE Y DEPARTAMENTO
        AND E.SALARIO > DS.SAL_MED --CONDICION DE QUE EL SALARIO SEA MAYOR QUE LA MEDIA
ORDER BY E.APELLIDO
;               


SELECT APELLIDO , SALARIO , DEPT_NO "CODIGO DEPARTAMENTO"
FROM EMPLE E
WHERE SALARIO >(SELECT SAL_MED
                FROM DEPT_SUM
                WHERE E.DEPT_NO = COD_DEPT)
ORDER BY E.APELLIDO
;
